// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvPMCRx0cwBMDCHA7hlwhbzxz-6zjtyQ',
    appId: '1:126381489756:web:e6b3d57ce0cd939992b099',
    messagingSenderId: '126381489756',
    projectId: 'flutter-masterclass-a4c5a',
    authDomain: 'flutter-masterclass-a4c5a.firebaseapp.com',
    storageBucket: 'flutter-masterclass-a4c5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghzsKnG_i8dAKgh8dqyVl3mtzGsvR1rI',
    appId: '1:126381489756:android:c8b4ffa0fc09357392b099',
    messagingSenderId: '126381489756',
    projectId: 'flutter-masterclass-a4c5a',
    storageBucket: 'flutter-masterclass-a4c5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFt7vo6ReBzG29rWiE6FTTCAYsa3LmNzI',
    appId: '1:126381489756:ios:a363b6b75b20d67792b099',
    messagingSenderId: '126381489756',
    projectId: 'flutter-masterclass-a4c5a',
    storageBucket: 'flutter-masterclass-a4c5a.firebasestorage.app',
    iosBundleId: 'com.example.fmcPart4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFt7vo6ReBzG29rWiE6FTTCAYsa3LmNzI',
    appId: '1:126381489756:ios:a363b6b75b20d67792b099',
    messagingSenderId: '126381489756',
    projectId: 'flutter-masterclass-a4c5a',
    storageBucket: 'flutter-masterclass-a4c5a.firebasestorage.app',
    iosBundleId: 'com.example.fmcPart4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpvPMCRx0cwBMDCHA7hlwhbzxz-6zjtyQ',
    appId: '1:126381489756:web:81ef888c43fb3f9292b099',
    messagingSenderId: '126381489756',
    projectId: 'flutter-masterclass-a4c5a',
    authDomain: 'flutter-masterclass-a4c5a.firebaseapp.com',
    storageBucket: 'flutter-masterclass-a4c5a.firebasestorage.app',
  );
}